(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='mseo-dashboard-posts-v1',SETKEY='mseo-dashboard-settings-v1';
let posts=[],media=[],client=null,toastTimer;
const sample=[{id:crypto.randomUUID(),title:'دليل تحسين المقالات لمحركات البحث',category:'SEO',status:'published',excerpt:'خطوات عملية لتحسين بنية المقال وظهوره في نتائج البحث.',body:'',slug:'seo-articles-guide',tags:'SEO, محتوى',image:'',updated:new Date().toISOString()},{id:crypto.randomUUID(),title:'كيف تبني خطة محتوى ناجحة لمدونتك؟',category:'التدوين',status:'draft',excerpt:'نظّم أفكارك وخطتك التحريرية في خطوات واضحة.',body:'',slug:'content-plan-blog',tags:'تدوين, محتوى',image:'',updated:new Date(Date.now()-86400000).toISOString()}];
function safeRead(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function persist(){localStorage.setItem(KEY,JSON.stringify(posts));render()}
function notify(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function date(v){try{return new Intl.DateTimeFormat('ar',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v))}catch{return '—'}}
function slugify(s){return s.trim().toLowerCase().replace(/[ًٌٍَُِّْـ]/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'')}
function escape(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusLabel(s){return s==='published'?'منشور':'مسودة'}
function render(){const published=posts.filter(p=>p.status==='published').length;$('#postCount').textContent=posts.length;$('#totalPosts').textContent=posts.length;$('#publishedPosts').textContent=published;$('#draftPosts').textContent=posts.length-published;$('#commentTotal').textContent='0';$('#statsPosts').textContent=posts.length;$('#publishRate').textContent=posts.length?Math.round(published/posts.length*100)+'%':'0%';$('#statsCategories').textContent=new Set(posts.map(p=>p.category).filter(Boolean)).size;
const recent=[...posts].sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,5);$('#recentPosts').innerHTML=recent.length?recent.map(p=>'<div class="recent-item"><div class="post-thumb">'+(p.image?'<img src="'+escape(p.image)+'" alt="">':'▤')+'</div><div class="recent-info"><b>'+escape(p.title)+'</b><small>'+escape(p.category||'بدون تصنيف')+' · '+date(p.updated)+'</small></div><span class="pill '+p.status+'">'+statusLabel(p.status)+'</span></div>').join(''):'<div class="empty-state"><span>▤</span><b>ابدأ بكتابة أول مقال</b><p>ستظهر مقالاتك الأخيرة هنا.</p></div>';
const q=($('#postSearch')?.value||'').trim().toLowerCase(),st=$('#statusFilter')?.value||'all',cat=$('#categoryFilter')?.value||'all';const filtered=[...posts].filter(p=>(p.title+' '+p.category+' '+p.tags).toLowerCase().includes(q)&&(st==='all'||p.status===st)&&(cat==='all'||p.category===cat)).sort((a,b)=>b.updated.localeCompare(a.updated));
$('#postsTable').innerHTML=filtered.map(p=>'<tr><td>'+escape(p.title)+'<div class="muted">'+escape(p.slug||'')+'</div></td><td>'+escape(p.category||'—')+'</td><td><span class="pill '+p.status+'">'+statusLabel(p.status)+'</span></td><td>'+date(p.updated)+'</td><td><div class="row-actions"><button data-edit="'+p.id+'">تعديل</button><button data-toggle="'+p.id+'">'+(p.status==='published'?'تحويل لمسودة':'نشر')+'</button><button class="delete" data-delete="'+p.id+'">حذف</button></div></td></tr>').join('');
$('#postsEmpty').hidden=filtered.length>0;const cats=[...new Set(posts.map(p=>p.category).filter(Boolean))].sort();const selected=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="all">كل التصنيفات</option>'+cats.map(c=>'<option value="'+escape(c)+'">'+escape(c)+'</option>').join('');$('#categoryFilter').value=cats.includes(selected)?selected:'all';$('#categoryList').innerHTML=cats.map(c=>'<option value="'+escape(c)+'"></option>').join('')}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const active=$('[data-view="'+name+'"]');$('#crumbTitle').textContent=active?active.textContent.trim().replace(/\d+/g,'').trim():name;$('#pageTitle').textContent=({overview:'صباح الإبداع 👋',posts:'مكتبة المقالات',pages:'الصفحات الثابتة',comments:'إدارة التعليقات',media:'مكتبة الوسائط',stats:'إحصاءات المدونة',seo:'مركز SEO',layout:'التخطيط والقوائم',theme:'المظهر والقوالب',settings:'إعدادات المدونة'})[name]||'لوحة التحكم';$('#pageSubtitle').textContent=({overview:'تابع محتواك وأدر مدونتك من مكان واحد.',posts:'أنشئ المحتوى وعدّله ونظّم حالات النشر.',seo:'حسّن عناوين المقالات وأوصافها وروابطها.',settings:'تحكم في هوية المدونة واتصال قاعدة البيانات.'})[name]||'أدوات مدونتك في مساحة عمل واحدة.';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function openEditor(p){$('#postForm').reset();$('#editId').value=p?.id||'';$('#editorHeading').textContent=p?'تعديل المقال':'إنشاء مقال';$('#postTitle').value=p?.title||'';$('#postCategory').value=p?.category||'';$('#postSlug').value=p?.slug||'';$('#postExcerpt').value=p?.excerpt||'';$('#postBody').value=p?.body||'';$('#postTags').value=p?.tags||'';$('#postImage').value=p?.image||'';$('#postModal').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('#postTitle').focus(),50)}
function closeEditor(){$('#postModal').hidden=true;document.body.style.overflow=''}
function savePost(status){const title=$('#postTitle').value.trim();if(!title){$('#postTitle').focus();notify('أدخل عنوان المقال أولاً.');return}const id=$('#editId').value||crypto.randomUUID(),old=posts.find(p=>p.id===id);const post={id,title,category:$('#postCategory').value.trim(),slug:$('#postSlug').value.trim()||slugify(title),excerpt:$('#postExcerpt').value.trim(),body:$('#postBody').value,tags:$('#postTags').value.trim(),image:$('#postImage').value.trim(),status,updated:new Date().toISOString()};posts=posts.filter(p=>p.id!==id);posts.unshift(post);persist();closeEditor();notify(status==='published'?'تم حفظ المقال كمنشور في هذا المتصفح.':'تم حفظ المسودة محلياً.');if(!old)showView('posts')}
$('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});$$('[data-goto]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.goto)));$$('[data-action="post"]').forEach(b=>b.addEventListener('click',()=>openEditor()));$$('[data-action="page"]').forEach(b=>b.addEventListener('click',()=>notify('إدارة الصفحات ستُفعّل بعد ربط قاعدة البيانات.')));
['#newPost','#newPostTop','#newPostList','#emptyNewPost'].forEach(s=>$(s)?.addEventListener('click',()=>openEditor()));$('#closeModal').addEventListener('click',closeEditor);$('#postModal').addEventListener('click',e=>{if(e.target===$('#postModal'))closeEditor()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#postModal').hidden)closeEditor()});$('#postTitle').addEventListener('input',()=>{if(!$('#postSlug').value||$('#postSlug').dataset.auto==='true'){$('#postSlug').value=slugify($('#postTitle').value);$('#postSlug').dataset.auto='true'}});$('#postSlug').addEventListener('input',()=>$('#postSlug').dataset.auto='false');$('#postForm').addEventListener('submit',e=>{e.preventDefault();savePost('published')});$('#saveDraft').addEventListener('click',()=>savePost('draft'));$('#postSearch').addEventListener('input',render);$('#statusFilter').addEventListener('change',render);$('#categoryFilter').addEventListener('change',render);
$('#postsTable').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const p=posts.find(x=>x.id===b.dataset.edit||x.id===b.dataset.toggle||x.id===b.dataset.delete);if(!p)return;if(b.dataset.edit)openEditor(p);if(b.dataset.toggle){p.status=p.status==='published'?'draft':'published';p.updated=new Date().toISOString();persist();notify('تم تحديث حالة المقال.')}if(b.dataset.delete&&confirm('هل تريد حذف المقال «'+p.title+'» نهائياً من هذا المتصفح؟')){posts=posts.filter(x=>x.id!==p.id);persist();notify('تم حذف المقال محلياً.')}});
$('#exportBtn').addEventListener('click',()=>{const data={format:'mseo-dashboard-backup-v1',exportedAt:new Date().toISOString(),posts,settings:safeRead(SETKEY,{})};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='mseo-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);notify('تم تجهيز النسخة الاحتياطية.')});$('#importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.format!=='mseo-dashboard-backup-v1'||!Array.isArray(d.posts))throw Error('bad');if(!confirm('سيتم استبدال المقالات المحلية الحالية. هل تتابع؟'))return;posts=d.posts.filter(p=>p&&typeof p.title==='string'&&p.id);localStorage.setItem(SETKEY,JSON.stringify(d.settings||{}));persist();notify('تم استيراد النسخة الاحتياطية.')}catch{notify('الملف غير صالح أو ليس نسخة MSEO احتياطية.')}finally{e.target.value=''}});
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('mseo-dashboard-dark',document.body.classList.contains('dark')?'1':'0')});if(localStorage.getItem('mseo-dashboard-dark')==='1')document.body.classList.add('dark');
$$('.theme-choice').forEach(b=>b.addEventListener('click',()=>{$$('.theme-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.documentElement.style.setProperty('--accent',({violet:'#7257e8',green:'#16875f',blue:'#3268c9'})[b.dataset.color]);document.documentElement.style.setProperty('--accent-soft',({violet:'#f0edff',green:'#e6f8f0',blue:'#e8f3ff'})[b.dataset.color]);localStorage.setItem('mseo-dashboard-accent',b.dataset.color)}));const savedColor=localStorage.getItem('mseo-dashboard-accent');if(savedColor){const b=$('[data-color="'+savedColor+'"]');b?.click()}
function seoUpdate(){$('#titleCount').textContent=$('#seoTitle').value.length;$('#descCount').textContent=$('#seoDescription').value.length;$('#previewTitle').textContent=$('#seoTitle').value||'عنوان الصفحة';$('#previewSlug').textContent=$('#seoSlug').value||'عنوان-المقال';$('#previewDescription').textContent=$('#seoDescription').value||'سيظهر الوصف التعريفي هنا.'}['#seoTitle','#seoDescription','#seoSlug'].forEach(s=>$(s).addEventListener('input',seoUpdate));$('#seoCheck').addEventListener('click',()=>{const t=$('#seoTitle').value.trim(),d=$('#seoDescription').value.trim(),slug=$('#seoSlug').value.trim(),items=[t.length>=30&&t.length<=60?'✓ طول العنوان مناسب مبدئياً.':'! حاول أن يكون العنوان بين 30 و60 حرفاً.',d.length>=70&&d.length<=160?'✓ طول الوصف مناسب مبدئياً.':'! اجعل الوصف مفيداً وواضحاً (نحو 70–160 حرفاً).',slug&&!/[\sA-Z]/.test(slug)?'✓ الرابط الدائم لا يحتوي مسافات أو أحرفاً لاتينية كبيرة.':'! راجع الرابط الدائم وأزل المسافات والأحرف الكبيرة.'];$('#seoResults').innerHTML=items.map(x=>'<div>'+escape(x)+'</div>').join('');});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const d={name:$('#blogName').value,description:$('#blogDescription').value,url:$('#blogUrl').value};localStorage.setItem(SETKEY,JSON.stringify(d));notify('تم حفظ الإعدادات في هذا المتصفح.')});const cfg=safeRead(SETKEY,{});if(cfg.name)$('#blogName').value=cfg.name;if(cfg.description)$('#blogDescription').value=cfg.description;if(cfg.url)$('#blogUrl').value=cfg.url;
$('#mediaFiles').addEventListener('change',e=>{for(const f of e.target.files){if(!f.type.startsWith('image/'))continue;const url=URL.createObjectURL(f);media.push({name:f.name,url});const item=document.createElement('div');item.className='media-item';const img=document.createElement('img');img.src=url;img.alt=f.name;const name=document.createElement('small');name.textContent=f.name;item.append(img,name);$('#mediaGrid').append(item)}$('#mediaEmpty').hidden=media.length>0;if(media.length)notify('تمت معاينة الصور محلياً؛ لم تُرفع إلى خادم.');e.target.value=''});
$('#supabaseForm').addEventListener('submit',async e=>{e.preventDefault();const url=$('#supabaseUrl').value.trim(),key=$('#supabaseKey').value.trim(),status=$('#supabaseStatus');if(!url||!key){status.textContent='أدخل الرابط والمفتاح العام أولاً.';return}if(!window.supabase?.createClient){status.textContent='تعذر تحميل مكتبة Supabase.';return}try{client=window.supabase.createClient(url,key);const {error}=await client.auth.getSession();if(error)throw error;status.textContent='تم الاتصال بخدمة Supabase. تسجيل الدخول وقاعدة البيانات لم يتم إعدادهما بعد.';$('#connectionText').textContent='تم تهيئة Supabase';notify('تم التحقق من إعداد العميل.')}catch(err){status.textContent='تعذر الاتصال: '+(err.message||'تحقق من الرابط والمفتاح وسياسات المشروع.');client=null}});
posts=safeRead(KEY,null);if(!Array.isArray(posts)){posts=sample;persist()}else render();$('#connectionText').textContent='التخزين المحلي نشط';
})();